### PR TITLE
send notification from dashboard

### PR DESCRIPTION
**Pull request by lienvdsteen**
announcement

### CODE REVIEW

**Comment by lienvdsteen** [comment]
@cmw0513 can you maybe suggest better wording?

**Comment by cmw0513** [comment]
Not sure what you mean? I think "add announcement" is good.  maybe not notification as much

**Comment by cmw0513** [comment]
How about "share something with your team"

**Comment by lienvdsteen** [comment]
i just felt like 'add a notification for the team' sounded a bit weird

**Pull request merged**
